name: 自动构建Windows可执行文件

on:
  push:
    branches: [ main, master ]
    tags: ['v*.*.*']
  pull_request:
    branches: [ main, master ]

jobs:
  # 构建作业 - 无论分支还是标签推送都会运行
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: 创建spec文件（如果不存在）
      run: |
        if (-not (Test-Path .\init.spec)) {
          pyinstaller --name "花名册管理工具" --onefile --windowed --icon=icon.ico init.py
        }

    - name: 构建可执行文件
      run: pyinstaller init.spec

    - name: 验证构建产物
      run: |
        # 列出dist目录内容，确认文件生成
        Write-Host "dist目录内容："
        Get-ChildItem -Path .\dist -Recurse
        
        # 检查文件是否存在
        if (Test-Path ".\dist\花名册管理工具.exe") {
          Write-Host "找到可执行文件：.\dist\花名册管理工具.exe"
        } else {
          Write-Host "错误：未找到可执行文件"
          Get-ChildItem -Path .\ -Recurse | Where-Object { $_.Extension -eq ".exe" }
        }

    - name: 准备发布资产
      run: |
        # 确保目标目录存在
        New-Item -ItemType Directory -Force -Path release_assets
        
        # 直接复制dist目录下的可执行文件
        Copy-Item -Path .\dist\花名册管理工具.exe -Destination .\release_assets\roster_manager.exe -Force
        
        # 验证复制结果
        Write-Host "release_assets目录内容："
        Get-ChildItem -Path .\release_assets -Recurse

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: roster_manager.exe
        path: .\release_assets\roster_manager.exe
        # 确保产物保留时间足够长
        retention-days: 30

  # 发布作业 - 仅在标签推送时运行
  release:
    needs: build
    runs-on: windows-latest
    # 只在标签推送时触发
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: 下载构建产物
      uses: actions/download-artifact@v4
      with:
        name: roster_manager.exe
        path: .\release_assets

    - name: 验证下载的产物
      run: |
        Write-Host "下载的产物内容："
        Get-ChildItem -Path .\release_assets -Recurse
        
        # 检查文件是否存在
        if (Test-Path ".\release_assets\roster_manager.exe") {
          Write-Host "找到下载的可执行文件"
        } else {
          Write-Host "错误：未找到下载的可执行文件"
        }

    - name: 创建GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        # 使用相对路径格式
        files: .\release_assets\roster_manager.exe
        # 使用tag名称作为release名称
        name: 版本 ${{ github.ref_name }}
        body: 自动构建的版本 ${{ github.ref_name }}
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
